[package]
name = "vcf_parser_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.1.1"
pyo3 = { version = "0.25.1", features = ["extension-module"] }
rust-htslib = "0.49.0"
thiserror = "2.0.12"

[lib]
name = "vcfparser"
crate-type = ["cdylib"]